// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/a1fbe3bc3f6d1256bd8635cc84c93cf8796c09ec/bootstrap-table/index.d.ts
interface JQuery {
    bootstrapTable(options?: any): JQuery;
}

declare var bootstrapTable: JQueryStatic;
